name = "SDP"
version = "0.1.0"
defaultTargets = ["sdp"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[lean_lib]]
name = "SDP"

[[lean_exe]]
name = "sdp"
root = "Main"
